spring:
  sql:
    init:
      data-locations: classpath:/sql/mysql/member/insert_member.sql, classpath:/sql/mysql/shippinginfo/insert_shipping_info.sql ,classpath:/sql/mysql/product/insert_product.sql,classpath:/sql/mysql/order/insert_order.sql, classpath:/sql/mysql/order/insert_order_product.sql,  classpath:/sql/mysql/product/insert_product_image.sql
      mode: always
      encoding: UTF-8
  datasource:
    password: 2H#@(#Jksj@kkwje
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: item-admin
    url: jdbc:log4jdbc:mysql://localhost:3307/item-browser?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
decorator:
  datasource:
    p6spy:
      enable-logging: true

app:
  domain: http://localhost:8080
logging:
  level:
    jdbc:
      audit: 'off'
      connection: 'off'
      sqlonly: info
      resultset: 'off'
      resultsettable: 'off'
      sqltiming: 'off'
    root: info